# Laboratorium 4 — NumPy zaawansowane
**Autor:** Jan Pyka

In [2]:
import numpy as np

## Ćwiczenie 1: Broadcasting — zastosowania biznesowe

In [3]:
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")

Kształt macierzy: (4, 3)


In [4]:
#Zadanie 1a
ceny_inflacja = ceny * 1.05
print(ceny_inflacja)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [6]:
#Zadanie 1b
rabaty = np.array([0.10, 0.05, 0.15])
ceny_rabat = ceny * (1-rabaty)
print(ceny_rabat)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [ ]:
#Zadanie 1c
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
ceny_marza = ceny * (1 + marza)
print(ceny_marza)

[[ 38.987   41.587   37.687 ]
 [ 69.986   74.186   67.186 ]
 [ 18.7375  19.9875  17.4875]
 [149.985  157.485  142.485 ]]


In [ ]:
#Zadanie 1d
najtansze = ceny.argmin(axis=1)
y = 1
for x in najtansze:
    print(f'Najtanszy sklep dla Produktu-{y} to {sklepy[x]}')
    y += 1

Najtanszy sklep dla Produktu-1 to Online
Najtanszy sklep dla Produktu-2 to Online
Najtanszy sklep dla Produktu-3 to Online
Najtanszy sklep dla Produktu-4 to Online


## Ćwiczenie 2: Reshape i łączenie danych

In [ ]:
#Zadanie 2a
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

In [23]:
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [24]:
#Zadanie 2b — Stacking
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

In [ ]:
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [42]:
#Zadanie 2c
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
#1 - Reshape na macierz 6×2
sprzedaz_macierz = sprzedaz_flat.reshape(6,2)
print(sprzedaz_macierz)
#2 - Oblicz średnią sprzedaż per produkt (axis=1)
srednie_ceny = sprzedaz_macierz.mean(axis=1)
print(srednie_ceny)
#3 - Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
print(sprzedaz_macierz[:, 1] - sprzedaz_macierz[:, 0])

[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
[150. 225. 215. 170. 240. 225.]
[100 150 -70 100 140 -70]


In [ ]:
#Zadanie 2d
nowe = wszystkie.flatten()
nowe = np.concatenate([nowe, np.array([235])])
print(nowe)

[150 160 170 180 120 130 140 150  90 100 110 120 235]


## Ćwiczenie 3: Analiza danych finansowych

In [44]:
#Dane
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [52]:
#Zadanie 3a
#1 - Oblicz średnią, medianę i odchylenie standardowe pensji
srednia = pensje.mean()
mediana = np.median(pensje)
odchylenie = pensje.std()
print(f'Srednia: {srednia} \nMediana: {mediana} \nOdchylenie: {odchylenie}')
print('\n')

#2 - Wyświetl imiona osób zarabiających powyżej średniej
pracownicy_arr = np.array(pracownicy)
maska_pracownicy = pensje > pensje.mean()
print(pracownicy_arr[maska_pracownicy])
print('\n')

#3 - Wyświetl imiona osób zarabiających poniżej mediany
maska_mediana = pensje < np.median(pensje)
print(pracownicy_arr[maska_mediana])
print('\n')

#4 - Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje,75) - np.percentile(pensje,25)
print(f'Rozstęp: {rozstep}, Rozstep miedzykwartylowy: {iqr}')

Srednia: 6425.0 
Mediana: 6050.0 
Odchylenie: 1616.9029037020127


['Jan' 'Marek' 'Zofia']


['Anna' 'Ewa' 'Piotr' 'Tomek']


Rozstęp: 4900, Rozstep miedzykwartylowy: 2200.0


In [ ]:
#Zadanie 3b
premie = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
wynagrodzenie = pensje + premie
print(wynagrodzenie)
print(pracownicy_arr[premie.argmax()])

[ 6500  7200  6800 10100  8300  4200  9500  5800]
Ewa


In [70]:
#Zadanie 3c
kolejnosc = np.argsort(pensje)[::-1]
for i, idx in enumerate(kolejnosc,1):
    print(f'Imie - {pracownicy_arr[idx]}, Pensja - {pensje[idx]}, Staz - {staz[idx]} lat')

Imie - Marek, Pensja - 9100, Staz - 15 lat
Imie - Zofia, Pensja - 8500, Staz - 12 lat
Imie - Jan, Pensja - 7200, Staz - 8 lat
Imie - Kasia, Pensja - 6300, Staz - 5 lat
Imie - Tomek, Pensja - 5800, Staz - 4 lat
Imie - Anna, Pensja - 5500, Staz - 3 lat
Imie - Ewa, Pensja - 4800, Staz - 2 lat
Imie - Piotr, Pensja - 4200, Staz - 1 lat


In [74]:
#Zadanie 3d
# Oblicz korelację: staż vs pensja
print(np.corrcoef(staz,pensje)[0,1])
# Oblicz korelację: staż vs ocena
print(np.corrcoef(staz,oceny)[0,1])
#Silniejszy jest zwiazek staz vs pensja

0.987862864584301
0.04198471605953068


In [78]:
#Zadanie 3e
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol
print(przychod.argmax(axis=1))
print(przychod.argmax(axis=0))
print(przychod[:, :3].sum())
print(przychod[:, 3:].sum())

[1 2 5 4]
[1 0 2 0 2 2]
2463950
2536500


## Ćwiczenie 4: Generowanie danych

In [80]:
np.random.seed(42)
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

In [85]:
#1 - Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, odchylenie: {wiek.std():.1f}, min: {wiek.min()} max: {wiek.max()}")
#2 - Korelacja wiek vs wydatki
print(f'Korelacja wiek vs wydatki: {np.corrcoef(wiek, wydatki)[0, 1]:.4f}')

Wiek — średnia: 33.6, mediana: 33.0, odchylenie: 8.6, min: 18 max: 53
Korelacja wiek vs wydatki: -0.1201


In [86]:
#3 - Korelacja wizyty vs wydatki
print(f'Korelacja wiek vs wydatki: {np.corrcoef(wizyty, wydatki)[0, 1]:.4f}')

Korelacja wiek vs wydatki: -0.1588


In [101]:
sr = wydatki.mean()
sd = wydatki.std()
segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI','ŚREDNI'))
print(segment)
wartosci = np.unique(segment, return_counts=True)
print(wartosci)


['NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI'
 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'NISKI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'WYSOKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'WYSOKI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI']
(array(['NISKI', 'WYSOKI', 'ŚREDNI'], dtype='<U6'), array([17, 12, 71]))
