# Laboratorium 3 — NumPy
**Autor:** Jan Pyka

In [2]:
import numpy as np

In [2]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")


Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [8]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


## Ćwiczenie 2: Indeksowanie i slicing

### Tablica 1D

In [9]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

In [10]:
#Sprzedaż w styczniu 
print(miesiace_sprzedaz[0])

120


In [11]:
#Sprzedaż w grudniu
print(miesiace_sprzedaz[-1])

221


In [12]:
#Sprzedaż w Q1
print(miesiace_sprzedaz[0:2])

[120 135]


In [13]:
#Sprzedaż w Q4
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [14]:
#Sprzedaz co drugi miesiac
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [15]:
#Sprzedaż od tyłu
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


### Macierz 2D

In [16]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']


In [20]:
#Sprzedaż Produktu A w Q2
print(dane[0,1])

145


In [21]:
#Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny)
print(dane[2])

[234 267 289]


In [23]:
#Sprzedaż wszystkich produktów w Q1
print(dane[:,0])

[120  89 234  56]


In [25]:
#Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2)
print(dane[1:3,1:3])

[[102  95]
 [267 289]]


## Ćwiczenie 3: Operacje wektorowe — analiza biznesowa

In [6]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

## Zadanie 1: Podstawowe statystyki cenowe
### Średnia cena, najdroższy produkt, najtańszy produkt

In [27]:
print(f'Średnia - {ceny.mean()}')
print(f'Max - {ceny.max()}')
print(f'Min - {ceny.min()}')
print(f'ArgMax - {ceny.argmax()}')
print(f'ArgMin - {ceny.argmin()}')

Średnia - 1171.0
Max - 3499
Min - 89
ArgMax - 0
ArgMin - 4


## Zadanie 2: Wartość magazynu
### Oblicz wartość każdego produktu (cena × ilość) i łączną wartość magazynu

In [ ]:
ceny_ilosc = ilosci_magazyn * ceny
suma_magazyn = ceny_ilosc.sum()
x = 0
while x < len(ceny_ilosc):
    print(f'{nazwy[x]} - łączna wartosc: {ceny_ilosc[x]}')
    x +=1
print(f'Wartość magazynu: {suma_magazyn}')

Laptop - łączna wartosc: 52485
Tablet - łączna wartosc: 79758
Smartfon - łączna wartosc: 194922
Słuchawki - łączna wartosc: 54444
Ładowarka - łączna wartosc: 27768
Klawiatura - łączna wartosc: 22161
Mysz - łączna wartosc: 25929
Monitor - łączna wartosc: 34477
Kamera - łączna wartosc: 26955
Drukarka - łączna wartosc: 30566
549465


## Zadanie 3: Analiza cenowa


In [45]:
# Stworz array z cenami po rabacie 15% (promocja świąteczna)
promocja_swiateczna = ceny * 0.85
print(promocja_swiateczna)

[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]


In [47]:
# Stworz array z cenami po uwzględnieniu VAT 23%
ceny_vat = ceny * 1.23
print(ceny_vat)

[4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]


In [52]:
# Ile produktów kosztuje powyżej 1000 zł?
print((ceny > 1000).sum())

4


## Zadanie 4: Filtrowanie
### Produkty z oceną >= 4.5 — nazwy i ceny
### Produkty poniżej 200 zł — nazwy i ilości w magazynie

In [16]:
# Podpowiedź: maska = oceny_klientow >= 4.5, potem ceny[maska]
# Uwaga: nazwy to zwykła lista — zamień ją na np.array(nazwy), żeby użyć maski
npceny = np.array(ceny)
npnazwy = np.array(nazwy)
npilosc = np.array(ilosci_magazyn)
maska_oceny = oceny_klientow >= 4.5
maska_cena = npceny < 200
print(f'Produkty z ocena >= 4.5: {npnazwy[maska_oceny]} Ceny: {npceny[maska_oceny]}')
print(f'Produkty z ceną poniżej 200zł: {npnazwy[maska_cena]} Ilosci: {npilosc[maska_cena]}')

Produkty z ocena >= 4.5: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor'] Ceny: [3499 2499  349 1499]
Produkty z ceną poniżej 200zł: ['Ładowarka' 'Mysz'] Ilosci: [312 201]


## Zadanie 5: Analiza zapasów
### Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy
### Łączna wartość tych produktów
### Ile % całego magazynu stanowią?

In [25]:
maska_ilosc = npilosc < 30
laczna_wartosc = (npilosc[maska_ilosc] * npceny[maska_ilosc]).sum()
proc_ilosc = round((((npilosc[maska_ilosc]).sum())/npilosc.sum())*100,1)
print(f'Produkty z niskim stanem mag. : {npnazwy[maska_ilosc]} ich łączna wartość to: {laczna_wartosc} stanowia one {proc_ilosc} % całego magazynu')

Produkty z niskim stanem mag. : ['Laptop' 'Monitor'] ich łączna wartość to: 86962 stanowia one 3.8 % całego magazynu


## Zadanie 6 (bonus): Analiza korelacji cena–ocena
### Które produkty są "okazją" — ocena >= 4.5 i cena < 1000 zł? Wypisz nazwy i ceny.
### Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?
### Podpowiedź: łączenie warunków: (warunek1) & (warunek2)


In [34]:
maska_cena2 = npceny < 1000
print(f'Okazje to: {npnazwy[(maska_oceny) & (maska_cena2)]} ich ceny to: {npceny[(maska_oceny) & (maska_cena2)]}')
maska_ocena = oceny_klientow >= 4
maska_ocena2 = oceny_klientow < 4
print(f'Średnia cena prod. >= 4.0 to: {round(npceny[maska_ocena].mean(),2)}')
print(f'Średnia cen prod. < 4.0 to: {round(npceny[maska_ocena2].mean(),2)}')

Okazje to: ['Słuchawki'] ich ceny to: [349]
Średnia cena prod. >= 4.0 to: 1446.14
Średnia cen prod. < 4.0 to: 529.0


## Ćwiczenie 4: Benchmark — lista vs NumPy

In [35]:
import time

In [36]:
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)


### Test 1: Pomnóż przez 2

In [37]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 76.0 ms
NumPy: 3.3 ms
NumPy jest 23× szybszy!


### Test 2: Suma

In [38]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")



=== Suma (1,000,000 elementów) ===
Lista: 21.4 ms
NumPy: 1.9 ms
NumPy jest 11× szybszy!


### Test 3: Filtrowanie (elementy > 500000)


In [39]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 42.2 ms
NumPy: 2.4 ms
NumPy jest 17× szybszy!


## Podsumowanie benchmarku
NumPy jest **23x** szybszy w mnozeniu <br>
NumPy jest **11x** szybszy w sumowaniu<br>
NumPy jest **17x** szybszy w filtrowaniu<br>
Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list